import "./globals.css";
import { space_grotesk_init, roboto_init } from './utils/fonts';


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className={`${space_grotesk_init.variable} ${roboto_init.variable}`}>
        {children}
      </body>
    </html>
  );
}
